config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'recipes#index'

  resources :recipes, only: %i[index show]

  # custom error endpoints
  match '*unmatched', to: 'application#route_not_found', via: :all
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ContentfulModel::Base
  # include Contentable
  self.content_type_id = 'recipe'

  def photo_url
    photo&.image_url
  end

  def tag_names
    tags&.map(&:name)
  end

  def chef_name
    chef&.name || 'Anonymous'
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper ContentfulRails::MarkdownHelper

  def route_not_found
    render file: Rails.public_path.join('404.html'), status: :not_found, layout: false
  end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  include RecipesHelper
  before_action :set_recipe, only: %i[show]

  def index
    @recipes = Recipe.all.skip(skip).limit(limit).load
    @total_recipes = @recipes.total
    @total_pages = total_pages(@total_recipes)
    @page = page
  end

  def show; end

  private

  def set_recipe
    @recipe ||= Recipe.find(params[:id])

    route_not_found if @recipe.blank?
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/recipes_helper.rb
# frozen_string_literal: true

module RecipesHelper
  def total_pages(total_count)
    (total_count.to_f / limit).ceil
  end

  def page
    (params[:page] || 1).to_i
  end

  def skip
    limit * (page - 1)
  end

  def limit
    (params[:per_page] || ENV['DEFAULT_PER_PAGE']).to_i
  end

  def page_link(page = 1)
    return recipes_path(page: 1, per_page: limit) if page < 2

    recipes_path(page: page, per_page: limit)
  end

  def pagination_data(total_pages)
    {
      current_page: page,
      last_page: total_pages,
      first_page_path: page_link(1),
      previous_page_path: page_link(page - 1),
      next_page_path: page_link(page + 1),
      last_page_path: page_link(total_pages)
    }
  end
end

app/views/layouts/_footer.html.erb
<div class="footer text-muted border">
  <div class="d-flex justify-content-around">
    <span class="">Spoonful</span>
    <span class="">
      <small>
        <%= Date.current.year %> © ChefRay Group
      </small>
    </span>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-light fixed-top">
<a class="navbar-brand" href=<%= root_path %>>
    <%= image_tag "logo.png", { width:"30", height:"30", class:"d-inline-block align-top", alt:"" }%>
    Spoonful
  </a>
</nav>

app/views/layouts/_pagination.html.erb
<nav aria-label="...">
  <ul class="pagination justify-content-center">
    <li class="page-item <%= data[:current_page] < 2 ? "disabled" : "" %>">
      <a class="page-link" href=<%= data[:first_page_path] %>>First page</a>
    </li>
    <% if data[:current_page] > 2 %>
      <li class="page-item">
        <a class="page-link" href=<%= data[:previous_page_path] %>>
          <%= data[:current_page] - 1 %>
        </a>
      </li>
    <% end %>
    <li class="page-item active">
      <span class="page-link">
        <%= data[:current_page] %>
        <span class="sr-only">(current)</span>
      </span>
    </li>
    <% if data[:current_page] < data[:last_page] - 1 %>
      <li class="page-item">
        <a class="page-link" href=<%= data[:next_page_path] %>>
          <%= data[:current_page] + 1 %>
        </a>
      </li>
    <% end %>
    <li class="page-item <%= data[:current_page] == data[:last_page] ? "disabled" : "" %>">
      <a class="page-link" href=<%= data[:last_page_path] %>>Last page</a>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spoonful</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="page-wrapper">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/recipes/index.html.erb
<div class="page recipes-index container">
  <div class="text-center">
    <h1>Browse Recipes</h1>
  </div>


  <% if @recipes.blank? %>
    <div class="text-center">
      <strong>No recipes to display</strong>
    <div>
  <% else %>
    <span class="text-muted">
      <small>
      Showing <%= @recipes.size %> of <%= @total_recipes %> recipes
      </small>
    <span>
    <div class="recipe-list-wrapper row justify-content-center">
      <% @recipes.each do |recipe|%>
        <div class="card col-md" style="width: 16rem;">
          <%= image_tag recipe.photo_url, { class: "card-img-top" } %>
          <div class="card-body">
            <h5 class="card-title"><%= recipe.title %></h5>
            <div class="text-center"><%= link_to "View", recipe_path(recipe.id), class: "btn btn-primary" %></div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <%= render 'layouts/pagination', data: pagination_data(@total_pages) %>
</div>

app/views/recipes/show.html.erb
<% cache @recipe do %>
  <div class="page container">
    <h1><%= @recipe.title %></h1>

    <div>
      <%= image_tag @recipe.photo_url, class: "img-fluid" %>
    </div>

    <div class="recipe-section-wrapper border">
      <div class="container fluid recipe-section">
        <% if @recipe.tag_names.present? %>
          <strong>Tags:</strong>
          <% @recipe.tag_names.each do |tag_name| %>
            <span class="badge badge-light"><%= tag_name %></span>
          <% end %>
        <% end %>
      </div>

      <div class="container-fluid recipe-section">
        <strong>Description:</strong>
        <%= parse_markdown(@recipe.description) %>
      </div>

      <div class="container-fluid recipe-section">
        <strong>Chef:</strong>
        <%= @recipe.chef_name %>
      </div>
    </div>

    <div class="text-center"><%= link_to "Go back", :back %></div>
  </div>
<% end %>